version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5432:5432"
    networks:
      - appnet

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:root@db:5432/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - appnet
  
  frontend:
    build: ./frontend
    networks:
      - appnet
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres-data:

networks:
  appnet:
